In [1]:
import numpy as np

In [6]:
array_1d = np.array(range(1,10))

In [7]:
array_1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
array_1d.ndim

1

In [5]:
array_1d.size

4

In [9]:
array_1d[array_1d > 5]

array([6, 7, 8, 9])

In [11]:
array_1d[(array_1d > 5) & (array_1d < 9)]

array([6, 7, 8])

In [12]:
array_1d


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
array_1d[array_1d%2 == 0]

array([2, 4, 6, 8])

In [23]:
np.where(array_1d > 3, "Greater than 3",np.where(array_1d<3,array_1d,"Less than 3"))

array(['1', '2', 'Less than 3', 'Greater than 3', 'Greater than 3',
       'Greater than 3', 'Greater than 3', 'Greater than 3',
       'Greater than 3'], dtype='<U14')

In [27]:
array_1d.mean()

5.0

In [29]:
array_2d= array_1d.reshape(3,3)

In [32]:
array_2d.sum(axis=0)

array([12, 15, 18])

In [31]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.median(array_2d)

5.0

In [34]:
np.unique(array_2d)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.sum(array_2d)

45

In [36]:
array_2d.sum()

45

In [40]:
np.sort(array_2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
array_2d[::-1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [4]:
import pandas as pd
series_2= pd.Series(["Day 1", "Day 2", "Day 3", "Day 4"] )

In [5]:
pd.DataFrame(
    {
        "id": [1,2],
        "store nmbr": [1,2],
        "family": ["Poultry", "Produce"]
        
        
    }


)

id  store nmbr   family
0   1           1  Poultry
1   2           2  Produce

In [47]:
oil= pd.read_csv("oil.csv")

In [48]:
oil

date  dcoilwtico
0     2013-01-01         NaN
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
...          ...         ...
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26
1218  2017-08-31       47.26

[1219 rows x 2 columns]

In [49]:
oil.columns = ["price_date","Oil_Price"]

In [50]:
oil

price_date  Oil_Price
0     2013-01-01        NaN
1     2013-01-02      93.14
2     2013-01-03      92.97
3     2013-01-04      93.12
4     2013-01-07      93.20
...          ...        ...
1214  2017-08-28      46.40
1215  2017-08-29      46.46
1216  2017-08-30      45.96
1217  2017-08-31      47.26
1218  2017-08-31      47.26

[1219 rows x 2 columns]

In [51]:
oil.iloc[:10,:]

price_date  Oil_Price
0  2013-01-01        NaN
1  2013-01-02      93.14
2  2013-01-03      92.97
3  2013-01-04      93.12
4  2013-01-07      93.20
5  2013-01-08      93.21
6  2013-01-09      93.08
7  2013-01-10      93.81
8  2013-01-11      93.60
9  2013-01-14      94.27

In [52]:
oil.loc[:5,"price_date":"Oil_Price"]

price_date  Oil_Price
0  2013-01-01        NaN
1  2013-01-02      93.14
2  2013-01-03      92.97
3  2013-01-04      93.12
4  2013-01-07      93.20
5  2013-01-08      93.21

In [53]:
oil.drop("price_date",axis=1)

Oil_Price
0           NaN
1         93.14
2         92.97
3         93.12
4         93.20
...         ...
1214      46.40
1215      46.46
1216      45.96
1217      47.26
1218      47.26

[1219 rows x 1 columns]

In [54]:
oil

price_date  Oil_Price
0     2013-01-01        NaN
1     2013-01-02      93.14
2     2013-01-03      92.97
3     2013-01-04      93.12
4     2013-01-07      93.20
...          ...        ...
1214  2017-08-28      46.40
1215  2017-08-29      46.46
1216  2017-08-30      45.96
1217  2017-08-31      47.26
1218  2017-08-31      47.26

[1219 rows x 2 columns]

In [55]:
oil.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1214    False
1215    False
1216    False
1217    False
1218     True
Length: 1219, dtype: bool

In [58]:
oil.drop_duplicates(keep = "last",inplace = True,ignore_index= True)

In [59]:
oil.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1213    False
1214    False
1215    False
1216    False
1217    False
Length: 1218, dtype: bool

In [60]:
oil.loc[oil["Oil_Price"]>100]

price_date  Oil_Price
131  2013-07-03     101.92
133  2013-07-05     103.09
134  2013-07-08     103.03
135  2013-07-09     103.46
136  2013-07-10     106.41
..          ...        ...
407  2014-07-24     102.76
408  2014-07-25     105.23
409  2014-07-28     105.68
410  2014-07-29     104.91
411  2014-07-30     104.29

[182 rows x 2 columns]

In [61]:
oil.describe()

Oil_Price
count  1175.000000
mean     67.714366
std      25.630476
min      26.190000
25%      46.405000
50%      53.190000
75%      95.660000
max     110.620000

In [65]:
oil.loc[oil['price_date'].str[:4]=="2013"]

price_date  Oil_Price
0    2013-01-01        NaN
1    2013-01-02      93.14
2    2013-01-03      92.97
3    2013-01-04      93.12
4    2013-01-07      93.20
..          ...        ...
256  2013-12-25        NaN
257  2013-12-26      99.18
258  2013-12-27      99.94
259  2013-12-30      98.90
260  2013-12-31      98.17

[261 rows x 2 columns]

In [66]:
oil


price_date  Oil_Price
0     2013-01-01        NaN
1     2013-01-02      93.14
2     2013-01-03      92.97
3     2013-01-04      93.12
4     2013-01-07      93.20
...          ...        ...
1213  2017-08-25      47.65
1214  2017-08-28      46.40
1215  2017-08-29      46.46
1216  2017-08-30      45.96
1217  2017-08-31      47.26

[1218 rows x 2 columns]